### ISSUE TITLE
Responsive ticket page

### ISSUE THREAD

**Issue by louziferr** [devhausleipzigacademy/camp12-midterm#104]
## Expected Behaviour

The final page of our application is the ticket page (where you see all the information about the bought ticket). It is displaying static information right now. Make the page responsive by passing the correct props to it when a ticket is bought. 

## Checklist

- [x] Check out the ticket page
- [x] get rid of the default prop arguments
- [x] change the seat-selection page and make it link to the ticket page
- [x] pass the correct props to the ticket page

**Comment by nakropin** [comment]
Had to refactor quite a lot just to get a grasp what is going on with the other pages. I wouldnt have called that an easy issue. Anyway - have fun merging, cheers!
