### ISSUE TITLE
Navbar Component

### ISSUE THREAD

**Issue by louziferr** [devhausleipzigacademy/camp12-midterm#35]
## Expected Behaviour

Implement the [Navbar Component](https://www.figma.com/design/TOCJzJFMXE7PL1dQyGWqXZ/midterm?node-id=193-51&t=lhuycxPj3Vpp8bXQ-0) for the Homepage.

## Checklist

- [x]  Get the SVGs to use for the navbar
- [x]  Put them in a component next to each other
- [x]  Give them a state for being active/inactive
- [x] Make sure just one can be active at one time

**Comment by dnmct** [comment]
I think this is already done! @louziferr
