### ISSUE TITLE
Fix Login Page

### ISSUE THREAD

**Issue by louziferr** [devhausleipzigacademy/camp12-midterm#58]
## Expected Behaviour

On the login page, there are two input components: one for email, one for password.

The email-field should have a mailbox-svg on the left instead of a search glass.

The password field should have a password-svg on the left. Also the input should be hidden.

## Checklist

- [x] Find two new svg's for the input fields.
- [x] Use them instead of the current svg's for the input fields.
- [x] Hide the password input field.
- [x] Check with a regex if the entered e-mail has an acceptable format.

**Comment by ShaQay3Q** [comment]
I think i have made all the asked changes.
