### ISSUE TITLE
Label component

### ISSUE THREAD

**Issue by louziferr** [devhausleipzigacademy/camp12-midterm#8]
## Expected Behaviour

We need a label component that is used to select the date and time for a booking
It has 3 states (unselected, selected, disabled)

## Checklist

_Detail the steps below to help us reproduce the problem you encountered._

- [x] Create component according to desgin https://www.figma.com/design/TOCJzJFMXE7PL1dQyGWqXZ/midterm?node-id=193-51&t=3bsn1O4cipxo3ue9-1
- [x] Define props (text and state

**Comment by AkimZmerli** [comment]
Added conditional styling for the three states disabled, selected and default.
