### ISSUE TITLE
Fetch movies from API on homepage

### ISSUE THREAD

**Issue by dnmct** [devhausleipzigacademy/camp12-midterm#80]
## Expected Behaviour

We need to display actual movies from the api on the homepage.
Currently they are still hardcoded

## Checklist

- [x] Use the correct query hook to fetch the movies
- [x] Map over them and show them in the reel

**Comment by nakropin** [comment]
Issue might have been already solved in #75-Genre-Select

**Comment by Fredmpk** [comment]
We are now adjusting the hook to make it a tanstack-query and then implement the new hook and the existing getMovies-hook
